publishDir = "./docs"
baseURL = "/"
defaultContentLanguage = "zh-cn"
theme = "hyde-y"

PaginatePath = "page"

title = "Hello World"
copyright = "@copyright 2017"

[author]
name = "TerryWu"
email = "terry.wuhao[at]gmail.com"
