baseurl = "http://blog.terrywh.net/"
languageCode = "zh-cn"
title = "Hello World"
theme = "hyde"
publishDir = "../blog"
defaultContentLanguage = "zh-cn"
disqusShortname = "terrywh"

[params]
  description = "Web Development by Go/Nodejs/PHP/C++"
  disqusShortname = "terrywh"
  thumbnailImage = true
  autoThumbnailImage = true

[[menu.main]]
  weight = 2
  name = "教程"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/tutorial"

[[menu.main]]
  weight = 1
  name = "笔记"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/notebook"

[[menu.main]]
  weight = 0
  name = "关于"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "https://github.com/terrywh"