cleanDestinationDir = true

baseURL = "https://blog.terrywh.net"
defaultContentLanguage = "zh-cn"
theme = "hyde-y"

title = "Hello World"
copyright = "@copyright 2017"

[author]
name = "TerryWu"
email = "terry.wuhao[at]gmail.com"

[params]
sidebar = "left"
topline = "C++/PHP/Go/NodeJS"
github = "terrywh"
rss = true
highlight = "tomorrow"

[taxonomies]
category = "categories"
tag = "tags"
book = "books"
